name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-targets
      - run: cargo test --no-run
